% ***********************************************************************/
% Function: modelGradients second stage
% ***********************************************************************/

function [  gradEnc, gradDec ] = ...
                        modelGradientsAE2( ...
                                        dlnetEnc, ...
                                        dlnetDec,  ...
                                        dlZ )

% calculate the KL-divergence
lossKL = klDivergence( dlZ );

% calculate the gradients (following igul222)
[ gradEnc, gradDec ] = dlgradient( lossKL, ...
                                   dlnetEnc.Learnables, ...
                                   dlnetDec.Learnables, ...
                                   'RetainData', true );


end